created: 2026-04-08T08:53:52.960Z
updated: 2026-04-08T09:56:14.170Z
update_count: 3
last_field: description
kind: nested-class
title: style-core
children:
  - config-module
  - style-utils
parentPath: []
