created: 2026-04-08T08:53:52.960Z
updated: 2026-04-08T08:57:07.150Z
update_count: 2
last_field: diagram
kind: nested-class
title: style-core
children:
  - config-module
  - style-utils
parentPath: []
