created: 2026-04-08T08:38:24.949Z
updated: 2026-04-08T09:53:42.998Z
update_count: 3
last_field: description
kind: nested-class
title: style-template-system
children:
  - config-module
  - style-utils
  - template-manager
parentPath: []
