created: 2026-04-08T08:38:24.949Z
updated: 2026-04-08T08:38:40.337Z
update_count: 2
last_field: diagram
kind: nested-class
title: style-template-system
children:
  - config-module
  - style-utils
  - template-manager
parentPath: []
