created: 2026-04-08T08:51:42.915Z
updated: 2026-04-08T09:55:43.059Z
update_count: 3
last_field: description
kind: nested-class
title: converter-modules
children:
  - docx-markdown-adapter
  - latex-analyzer
  - latex-converter
  - markdown-converter
  - smart-formatter
parentPath: []
