created: 2026-04-08T08:50:04.709Z
updated: 2026-04-08T09:55:40.457Z
update_count: 3
last_field: description
kind: nested-class
title: ui-modules
children:
  - main-window
  - smart-format-page
  - ui-components
  - ui-styles
parentPath: []
