created: 2026-04-08T08:41:52.489Z
updated: 2026-04-08T09:54:17.303Z
update_count: 3
last_field: description
kind: nested-class
title: preview-mapping
children:
  - docx-preview
  - latex-preview
  - mapping-state
  - markdown-preview
parentPath: []
