created: 2026-04-08T08:45:13.624Z
updated: 2026-04-08T09:55:00.803Z
update_count: 3
last_field: description
kind: nested-class
title: conversion-pipeline
children:
  - docx-roundtrip
  - final-save
  - latex-direct
  - markdown-direct
  - markdown-render
parentPath: []
