created: 2026-04-08T08:34:58.599Z
updated: 2026-04-08T09:53:40.949Z
update_count: 3
last_field: description
kind: nested-class
title: analysis-layer
children:
  - docx-analyzer
  - latex-analyzer
  - markdown-preview
  - preview-model
parentPath: []
