created: 2026-04-08T08:30:40.454Z
updated: 2026-04-08T09:52:58.003Z
update_count: 8
last_field: note
git_commit: 45b2697
git_branch: refactor/optimize-conversion-stability
children:
  - analysis-layer
  - conversion-layer
  - launcher
  - style-template-system
  - ui-shell
