created: 2026-04-08T08:51:27.504Z
updated: 2026-04-08T09:55:40.365Z
update_count: 3
last_field: description
kind: nested-class
title: analyzer-modules
children:
  - docx-analyzer
  - latex-analyzer
parentPath: []
