created: 2026-04-08T08:55:54.769Z
updated: 2026-04-08T09:56:14.116Z
update_count: 3
last_field: description
kind: nested-class
title: test-suite
children:
  - conversion-tests
  - template-tests
parentPath: []
